### ISSUE TITLE
[Feature] useBoolean, useDisclosure, useCheckbox, useSwitch, 

### ISSUE THREAD

**Issue by dev2820** [Rapiders/react-hooks#14]
## Describe the solution you'd like

boolean을 기반으로하는 ui용 훅을 구현합니다.

- useBoolean: true, false한 값을 결정하는 훅
- useDisclosure: open 상태를 가지는 훅
- useCheckbox: checked 상태를 가지는 훅
- useSwitch: on 상태를 가지는 훅

- [x] useBoolean 구현
    - [x] useDisclosure 구현
    - [ ] useCheckbox 구현
    - [x] useSwitch 구현

**Comment by dev2820** [comment]
안녕하세요 기여하러왔습니다. 시간날때 할게요 :)

**Comment by d0422** [comment]
안녕하세요! 기여 해주셔서 감사합니다! ☺️
오픈소스로 프로젝트를 진행하고자 하는데 부족한 점이 많습니다. 
기여뿐만 아니라 오픈소스 프로젝트로써 부족한 점이 있다면 편하게 의견주세용
다시 한 번 감사드립니당

**Comment by dev2820** [comment]
@d0422 혹시 기여할 때 fork떠서 해야하나요?

**Comment by d0422** [comment]
> @d0422 혹시 기여할 때 fork떠서 해야하나요?

오 네 fork 떠서 PR남겨주시면 좋을것 같습니다!

**Comment by dev2820** [comment]
최근에 일이 바빠서 useCheckbox 구현은 미뤄야할 것 같습니다. ㅠㅠ
관련 이슈를 계속 열어놓기 좀 그래서 useCheckbox는 다른 이슈 통해서 구현할게요
